# Etapa de compilación
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["APISitemaVentaDrogeria_03/APISitemaVentaDrogeria_03.csproj", "APISitemaVentaDrogeria_03/"]
RUN dotnet restore "APISitemaVentaDrogeria_03/APISitemaVentaDrogeria_03.csproj"
COPY . .
WORKDIR "/src/APISitemaVentaDrogeria_03"
RUN dotnet publish -c Release -o /app/publish

# Etapa de runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "APISitemaVentaDrogeria_03.dll"]
